### ISSUE TITLE
重复签到退出code错误

### ISSUE THREAD

**Issue by talking-toaster** [y1ndan/genshin-impact-helper#1]
![image](https://user-images.githubusercontent.com/49156890/97528834-956daf80-19e9-11eb-9353-530140488d7a.png)
如28号已经签过到了，再设置action会签到失败，导致后面不能自动定时执行；必须第二天没签过时再手动执行一次
建议区分将重复签到退出code也设成0

**Comment by y1ndan** [comment]
你昨天有设置过吗？经测试，即使昨天失败今天也会自动定时执行的

**Comment by talking-toaster** [comment]
昨天试过，手动两次都是重复签到，然后今天一直到中午都没有自动签到，然后手动是成功的
![image](https://user-images.githubusercontent.com/49156890/97529730-7bcd6780-19eb-11eb-863a-f59c4e37d960.png)
z最上面是刚刚中午手动run workflow

**Comment by y1ndan** [comment]
fixed
