### ISSUE TITLE
好兄弟考虑加个推送吗

### ISSUE THREAD

**Issue by chenkid999** [y1ndan/genshin-impact-helper#118]
企业微信应用消息推送，api文档我都找好了
https://work.weixin.qq.com/api/doc/90000/90135/90236

**Comment by y1ndan** [comment]
现在有个企业微信bot接口推送，你可以试试能不能用

**Comment by chenkid999** [comment]
> 现在有个企业微信bot接口推送，你可以试试能不能用

那个接口要下载企业微信才能看到信息，这个可以在普通微信上看到

**Comment by y1ndan** [comment]
可以试试替换[notify](https://raw.githubusercontent.com/y1ndan/genshin-impact-helper/wechat/notify.py)这个文件 我没有access_token无法调试

**Comment by chenkid999** [comment]
> 可以试试替换[notify](https://raw.githubusercontent.com/y1ndan/genshin-impact-helper/wechat/notify.py)这个文件 我没有access_token无法调试

嗯，晚点我试试

**Comment by chenkid999** [comment]
> 
> 
> > 可以试试替换[notify](https://raw.githubusercontent.com/y1ndan/genshin-impact-helper/wechat/notify.py)这个文件 我没有access_token无法调试
> 
> 嗯，晚点我试试

报错了
https://github.com/chenkid999/genshin-impact-helper/runs/1761476021?check_suite_focus=true

**Comment by y1ndan** [comment]
333行 `'touser': Notify.WW_USER_ID`后面加个分号，变成`'touser': Notify.WW_USER_ID,`

**Comment by chenkid999** [comment]
> 
> 
> 333行 `'touser': Notify.WW_USER_ID`后面加个分号，变成`'touser': Notify.WW_USER_ID,`

接口返回信息是msgtype格式错误
https://github.com/chenkid999/genshin-impact-helper/actions/runs/509193105

**Comment by y1ndan** [comment]
340行 `data=data`改成`json=data`如何

**Comment by chenkid999** [comment]
> 
> 
> 340行 `data=data`改成`json=data`如何

改了之后提示少了个参数，我给补上去了，现在可以正常推送，我提了个pr过去

**Comment by y1ndan** [comment]
> > 340行 `data=data`改成`json=data`如何
> 
> 改了之后提示少了个参数，我给补上去了，现在可以正常推送，我提了个pr过去

OK
