### ISSUE TITLE
请在米游社App内打开~

### ISSUE THREAD

**Issue by s-charvin** [y1ndan/genshin-impact-helper#124]
"result": "Failed",
  "message": "{\"data\": null, \"message\": \"请在米游社App内打开~\", \"retcode\": -1104}"

**Comment by y1ndan** [comment]
请看`readme`文档同步部分说明

**Comment by s-charvin** [comment]
> 请看`readme`文档同步部分说明

谢谢作者。没有仔细看文档，麻烦作者啦

**Comment by y1ndan** [comment]
Duplicate with #56
