### ISSUE TITLE
Is it possible to use on EU/NA ? 

### ISSUE THREAD

**Issue by BelovedTomboyishGirl** [y1ndan/genshin-impact-helper#129]
Hello,

Is it possible to use this script for NA and EU servers ?

Thanks.
(And sorry for not speaking chinese ^^")

**Comment by y1ndan** [comment]
I am sorry to tell you that it is impossible. Because this reward comes from the miHoYo BBS' activity. See [here](https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501)
As far as I know only official and bilibili servers are supported.
