### ISSUE TITLE
登陆上去了，也签到成功了，但是过一会就报错的情况。【附日志】

### ISSUE THREAD

**Issue by DeSireFire** [y1ndan/genshin-impact-helper#13]
```text
2020-11-05T07:00:42 INFO {
  "result": "Success",
  "message": "{\"data\": null, \"message\": \"旅行者,你已经签到过了\", \"retcode\": -5003}"
}
2020-11-05T07:00:42 INFO Sleep for 71 seconds ...
2020-11-05T07:01:56 INFO {
  "result": "Failed",
  "message": "\"{'data': None, 'message': '登录失效，请重新登录', 'retcode': -100}\""
}
Error: Process completed with exit code 123.
```
就一分钟的时间就会出现失效，我重新换了cookie还是会这样。
或者重启一次workflow也会这样，这是正常的吗？

**Comment by y1ndan** [comment]
官服？多cookie还是单cookie？重新触发workflow试试。正常只有一个success的提示

**Comment by DeSireFire** [comment]
> 官服？多cookie还是单cookie？重新触发workflow试试。正常只有一个success的提示

是的，官服。
单cookie。
我试过delete workflow run ,再run 一次也是会这样的。

这次我重新登陆一次网页米游社，把cookie更新上github去，
然后我把米游社app，游戏全关闭了,
又运行了一次workflow。

估计有什么操作把cookie刷新了，目前运行5分钟了，我观察观察。

**Comment by y1ndan** [comment]
重新fork试试 workflow不用同时运行多次

**Comment by DeSireFire** [comment]
> 重新fork试试 workflow不用同时运行多次 点一次run workflow 然后等待直到出现勾或叉再操作

目前为止是正常运行了，估计问题还是出在cookie上了，我没具体去检查是cookie少了什么键值对导致的。

感谢y1ndan哒！已经正常运行了。
