### ISSUE TITLE
怎么把他下载到自己的服务器上定时运行呢

### ISSUE THREAD

**Issue by czw63** [y1ndan/genshin-impact-helper#131]
是这样的。
我尝试让guthub定时运行可是他却没有，可能是我的操作失误把
但我正好有个闲置vps，想让他运行点东西（）

**Comment by y1ndan** [comment]
兑换码领取只需在secret里配置`KA_COOKIE`

微博签到推荐本地运行
- 安装 python 环境
- 下载最新代码：
  `git clone https://github.com/y1ndan/genshin-impact-helper.git`
- 进入 genshin-impact-helpe 目录
- 编辑 weibo.py 文件，跳到 220行 左右，按照注释填写 WB_COOKIE 和 KA_COOKIE 这两个值，保存。
- 终端输入 python3 ./weibo.py 运行脚本
- 定时运行可借助 cron 等工具

**Comment by y1ndan** [comment]
> 尝试让guthub定时运行可是他却没有

看看这位同学分享的心得 #134 ，没准是这个原因。
