### ISSUE TITLE
将项目设置为self-hosted后，github这边的build历史上，所有的汉字及表情有关的字符为乱码

### ISSUE THREAD

**Issue by davidelectricfree** [y1ndan/genshin-impact-helper#133]
将项目设置为self-hosted后，把该项目任务写成服务，同时使用带有管理员权限的账户运行，github这边的build历史上，所有的汉字及表情有关的字符为乱码，同时，无法将签到的结果输出给notify.py，且卡在准备推送通知这里（当然，这里显示的汉字也是乱码）。

系统：windows 10 x64  [版本 10.0.19042.804]
Python版本及其他action需要的依赖环境均为 在设置self-hosted时，脚本自动安装。

不知道是什么原因导致的汉字乱码。很希望能够用到这个程序的微博签到功能，这个工具确实好。
![3](https://user-images.githubusercontent.com/36690822/108479270-79f81e80-72d0-11eb-82a1-52d37bf55b43.jpg)

**Comment by y1ndan** [comment]
self-hosted 没试过。
可以尝试完全本地运行微博脚本。参考 #131
