### ISSUE TITLE
多cookie最后一个账号执行问题

### ISSUE THREAD

**Issue by WeberKang** [y1ndan/genshin-impact-helper#136]
多个账号导致最后一个能签到，但推送sc显示all 3 http requests failed，die。同时github邮件报failed。单账号不加#没问题

**Comment by davidelectricfree** [comment]
说实话，我也是多账号，没遇到你说的问题

**Comment by ShiroMaple** [comment]
请问多账号COOKIE怎么写？用什么格式分隔？

**Comment by devioa** [comment]
> 请问多账号COOKIE怎么写？用什么格式分隔？

比如你三个账号的cookie复制出来是id=1234，id=5678，id=90123。那么就用#把这三个连接起来就行，比如id=1234#id=5678#id=90123

**Comment by WeberKang** [comment]
我是用三台电脑用方法1获得cookie，但各个cookie内容，有些有别的参数。用#做的分割。三个号最后一个总是执行失败，不管调整cookie顺序报错http requests failed。

**Comment by Dimlitter** [comment]
回复

------------------ 原始邮件 ------------------


    
        发件人: WeberKang  <notifications@github.com>;
    
    
        发送时间: 2021-03-05 14:33:35
    
    
        收件人: y1ndan/genshin-impact-helper  <genshin-impact-helper@noreply.github.com>; 
    
    
        抄送: Subscribed  <subscribed@noreply.github.com>; 
    
    
        主题: Re: [y1ndan/genshin-impact-helper] 多cookie最后一个账号执行问题 (#136)
    

 Reopened #136.  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
