### ISSUE TITLE
配置代码同步失败

### ISSUE THREAD

**Issue by Wszl** [y1ndan/genshin-impact-helper#139]
按照流程配置自动同步代码，提示
.github/pull.yml file has failed validation

文件内容
.github/pull.yml 
`version: "1"
rules:                         # Array of rules
  - base: master               # Required. Target branch
    upstream: y1ndan:master    # Required. Must be in the same fork network.
    mergeMethod: merge     # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true        # Optional, merge pull request even when the mergeable_state is not clean. Default: false`

**Comment by y1ndan** [comment]
多次尝试都失败了么

**Comment by y1ndan** [comment]
另一种验证方法：
`https://pull-validation-uxx737qt0sl1.runkit.sh/?url=https://raw.githubusercontent.com/${owner}/genshin-impact-helper/master/.github/pull.yml`
将链接中`${owner} `改成你的github id

**Comment by Wszl** [comment]
> 
> 
> 另一种验证方法：
> `https://pull-validation-uxx737qt0sl1.runkit.sh/?url=https://raw.githubusercontent.com/${owner}/genshin-impact-helper/master/.github/pull.yml`
> 将链接中`${owner} `改成你的github id

谢谢这种方式成功了
