### ISSUE TITLE
为什么一直签到失败呢，提示“登录失效，请重新登录”

### ISSUE THREAD

**Issue by devioa** [y1ndan/genshin-impact-helper#140]
COOKIE我没弄错啊更新过好几次都是一样的，为什么还是这样呢

**Comment by davidelectricfree** [comment]
要么是你secret那里名字写错了，要么就是你cookie写错了

**Comment by devioa** [comment]
> 要么是你secret那里名字写错了，要么就是你cookie写错了
secret那里不是COOKIE吗，cookie是直接用脚本在console里复制出来的，然后粘贴到secret里的

**Comment by devioa** [comment]
> 要么是你secret那里名字写错了，要么就是你cookie写错了

secret那里不是COOKIE吗，cookie是直接用脚本在console里复制出来的，然后粘贴到secret里的

**Comment by y1ndan** [comment]
cookie里有没有account_id 和cookie_token

**Comment by devioa** [comment]
> cookie里有没有account_id 和cookie_token

没有，只有_MHYUUID; UM_distinctid; ltoken; ltuid; mi18nLang; CNZZDATA1275023096

**Comment by y1ndan** [comment]
> > cookie里有没有account_id 和cookie_token
> 
> 没有，只有_MHYUUID; UM_distinctid; ltoken; ltuid; mi18nLang; CNZZDATA1275023096

获取cookie不正确。

可以尝试清除缓存，隐身窗口登录，刷新页面后获取

**Comment by devioa** [comment]
> > > cookie里有没有account_id 和cookie_token
> > 
> > 
> > 没有，只有_MHYUUID; UM_distinctid; ltoken; ltuid; mi18nLang; CNZZDATA1275023096
> 
> 获取cookie不正确。
> 
> 可以尝试清除缓存，隐身窗口登录，刷新页面后获取

可以了，谢谢！
