### ISSUE TITLE
国际服上线签到了，我试了下不行，大佬帮忙看看

### ISSUE THREAD

**Issue by ilmen1988** [y1ndan/genshin-impact-helper#142]
2021-03-01T15:39:29 INFO 🌀原神签到小助手 v1.6.11
2021-03-01T15:39:29 INFO 若签到失败, 请尝试更新!
2021-03-01T15:39:29 INFO 任务开始
2021-03-01T15:39:29 INFO 检测到共配置了 6 个帐号
2021-03-01T15:39:29 INFO 准备为 NO.1 账号签到...
2021-03-01T15:39:29 INFO 准备获取账号信息...
2021-03-01T15:39:30 ERROR 	NO.1 账号:
    登录失效，请重新登录
2021-03-01T15:39:30 INFO 准备为 NO.2 账号签到...
2021-03-01T15:39:30 INFO 准备获取账号信息...

用教程试了cookie填入，然后分割账号，提示如上，是不是这样不行了？

**Comment by ilmen1988** [comment]
多账号是按照格式要求分开：_MHYUUID=……ltuid=……#_MHYUUID=……ltuid=……#_MHYUUID=……ltuid=…… 来分割的

**Comment by devioa** [comment]
cookie里有没有account_id 和cookie_token

_Originally posted by @y1ndan in https://github.com/y1ndan/genshin-impact-helper/issues/140#issuecomment-787266429_

**Comment by y1ndan** [comment]
要适配的 不通用

**Comment by grasssand** [comment]
改 `settingds.py`
``` python
class _Config:
    GIH_VERSION = ''
    WBH_VERSION = '1.0.2'
    ACT_ID = 'e202102251931481'
    GAME_BIZ = 'hk4e_global'
    REGION = 'os_asia' # os_usa|os_euro|os_asia|os_cht
    APP_VERSION = '2.3.0'
    REFERER_URL = 'https://webstatic-sea.mihoyo.com/ys/event/signin-sea/index.html?' \
                  'lang=en-us&act_id={}'.format(ACT_ID)
    AWARD_URL = 'https://hk4e-api-os.mihoyo.com/event/sol/home?lang=en-us&act_id={}'.format(ACT_ID)
    ROLE_URL = 'https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie?' \
               'game_biz={}&region={}'.format(GAME_BIZ, REGION)
    INFO_URL = 'https://hk4e-api-os.mihoyo.com/event/sol/info?lang=en-us&act_id={}'.format(ACT_ID)
    SIGN_URL = 'https://hk4e-api-os.mihoyo.com/event/sol/sign?lang=en-us'
    USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36'
    # weibo
    CONTAINER_ID = '100808fc439dedbb06ca5fd858848e521b8716'
    SUPER_URL = 'https://m.weibo.cn/api/container/getIndex?containerid={}'.format('100803_-_page_my_follow_super')
    YS_URL = 'https://m.weibo.cn/api/container/getIndex?containerid={}_-_feed'.format(CONTAINER_ID)
    KA_URL = 'https://ka.sina.com.cn/innerapi/draw'
    BOX_URL = 'https://ka.sina.com.cn/html5/mybox'
    WB_USER_AGENT = 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E150'
```
有待测试，先明天看看结果

**Comment by scottzzll** [comment]
> 改 `settings.py`
> 
> ```python
> 类 _config：
>      GIH_VERSION  =  '' 
>     WBH_VERSION  =  '1.0.2' 
>     ACT_ID  =  'e202102251931481' 
>     GAME_BIZ  =  'hk4e_global' 
>     REGION  =  'os_asia'  ＃os_usa | os_euro | os_asia | os_cht 
>     APP_VERSION  =  '2.3.0' 
>     REFERER_URL  = 的“https：/ /webstatic-sea.mihoyo.com/ys/event/signin-sea/index.html？' \
>                    'lang = zh-CN＆act_id = {}'。格式（ACT_ID）
>      AWARD_URL  =  'https: //hk4e-api-os.mihoyo.com/event/sol/home? lang = zh- CN &格式（ACT_ID）
>      ROLE_URL  =  'https: //api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie ？' \
>                 'game_biz = {}＆region = {}'。格式（GAME_BIZ，区域）
>      INFO_URL  =  'https: //hk4e-api-os.mihoyo.com/event/sol/info?lang = zh-CN & act_id = {}'。格式（ACT_ID）
>      SIGN_URL  =  'https: 
>     //hk4e-api-os.mihoyo.com/event/sol/sign  ? lang =  zh-cn'USER_AGENT = 'Mozilla / 5.0（X11; Linux x86_64）AppleWebKit / 537.36（KHTML ，例如Gecko）Chrome / 88.0.4324.182 Safari / 537.36'
>     ＃微博
>     CONTAINER_ID  =  '100808fc439dedbb06ca5fd858848e521b8716' 
>     SUPER_URL  =  'https://m.weibo.cn/api/container/getIndex?containerid= {}'。格式（'100803 _-__ page_my_follow_super'）
>      YS_URL  =  'https: //m.weibo.cn/api/container/getIndex? containerid ={ }_-_feed '。格式（CONTAINER_ID）
>      KA_URL  =  'https: 
>     //ka.sina.com.cn/innerapi/draw'BOX_URL  =  'https: 
>     //ka.sina.com.cn/html5/mybox'WB_USER_AGENT  = 'Mozilla / 5.0（iPhone； CPU iPhone OS 14_0_1，例如Mac OS X）AppleWebKit / 605.1.15（KHTML，例如Gecko）Mobile / 15E150'
> ```
> 
> 有待测试，先明天看看结果

我试过运行，仍旧提示“登录失效，请重新登录“，可以明天看下是否能成功

**Comment by y1ndan** [comment]
有国际服账号的可以测试下：
- 更新一下仓库
- 到https://www.hoyolab.com/genshin/获取cookie
- 照葫芦画瓢配置一个`OS_COOKIE`的secret变量
- 手动触发一次`Genshin Impact Helper Global `action
只是初步做了功能，之后慢慢改代码，欢迎反馈

**Comment by scottzzll** [comment]
> 有国际服账号的可以测试下：
> 
> * 更新一下仓库
> * 到https://www.hoyolab.com/genshin/获取cookie，确保cookie中有account_id，cookie_token，ltoken三个变量
> * 照葫芦画瓢配置一个`OS_COOKIE`的secret变量
> * 手动触发一次`Genshin Impact Helper Global `动作
> 
> 只是初步做了功能，之后慢慢改写代码，欢迎反馈

目前显示成功签到~

**Comment by ilmen1988** [comment]
> 
> 
> 有国际服账号的可以测试下：
> 
>     * 更新一下仓库
> 
>     * 到 https://www.hoyolab.com/genshin/ 获取cookie，确保cookie中有account_id，cookie_token，ltoken三个字段
> 
>     * 照葫芦画瓢配置一个`OS_COOKIE`的secret变量
> 
>     * 手动触发一次`Genshin Impact Helper Global `action
> 
> 
> 只是初步做了功能，之后慢慢改代码，欢迎反馈

尝试了，用`COOKIE`变量配置可以签到成功了，谢谢大佬

**Comment by y1ndan** [comment]
> > 有国际服账号的可以测试下：
> > ```
> > * 更新一下仓库
> > 
> > * 到 https://www.hoyolab.com/genshin/ 获取cookie，确保cookie中有account_id，cookie_token，ltoken三个字段
> > 
> > * 照葫芦画瓢配置一个`OS_COOKIE`的secret变量
> > 
> > * 手动触发一次`Genshin Impact Helper Global `action
> > ```
> > 
> > 
> > 只是初步做了功能，之后慢慢改代码，欢迎反馈
> 
> 尝试了，用`COOKIE`变量配置可以签到成功了，谢谢大佬

你除了亚服还有其他服的账号签到吗

**Comment by ilmen1988** [comment]
> 
> 
> > > 有国际服账号的可以测试下：
> > > ```
> > > * 更新一下仓库
> > > 
> > > * 到 https://www.hoyolab.com/genshin/ 获取cookie，确保cookie中有account_id，cookie_token，ltoken三个字段
> > > 
> > > * 照葫芦画瓢配置一个`OS_COOKIE`的secret变量
> > > 
> > > * 手动触发一次`Genshin Impact Helper Global `action
> > > ```
> > > 
> > > 
> > > 只是初步做了功能，之后慢慢改代码，欢迎反馈
> > 
> > 
> > 尝试了，用`COOKIE`变量配置可以签到成功了，谢谢大佬
> 
> 你国际服除了亚服还有其他服的账号签到吗

我只有亚服号，没其他服的

**Comment by y1ndan** [comment]
好的 解決了关闭下issue吧

**Comment by ilmen1988** [comment]
> 
> 
> > > 有国际服账号的可以测试下：
> > > ```
> > > * 更新一下仓库
> > > 
> > > * 到 https://www.hoyolab.com/genshin/ 获取cookie，确保cookie中有account_id，cookie_token，ltoken三个字段
> > > 
> > > * 照葫芦画瓢配置一个`OS_COOKIE`的secret变量
> > > 
> > > * 手动触发一次`Genshin Impact Helper Global `action
> > > ```
> > > 
> > > 
> > > 只是初步做了功能，之后慢慢改代码，欢迎反馈
> > 
> > 
> > 尝试了，用`COOKIE`变量配置可以签到成功了，谢谢大佬
> 
> 你国际服除了亚服还有其他服的账号签到吗

我只有亚服号，没其他服的
