### ISSUE TITLE
国服无法登录，求解

### ISSUE THREAD

**Issue by Accessiry** [y1ndan/genshin-impact-helper#147]
试了很多次都显示登陆失败，求大佬帮助
![G3 T( %7$MU$NRUSE试了很多次都显示登陆失败，求大佬帮助
9KD](https://user-images.githubusercontent.com/79847648/109576092-17075280-7b2e-11eb-9879-9373ef0f8853.png)

**Comment by y1ndan** [comment]
参考#14 #140

**Comment by Accessiry** [comment]
> 参考#14 #140
解决了！感谢大佬
