### ISSUE TITLE
請問該怎麼開啟TG的推播通知

### ISSUE THREAD

**Issue by NeiL978** [y1ndan/genshin-impact-helper#148]
我設定了TG_BOT_TOKEN及TG_USER_ID了 但是沒有推播通知出現
TG_USER_ID的值是輸入我的使用者名稱? 前面需要@嗎?
圖片看起來我的TG推播沒有開啟
![image](https://user-images.githubusercontent.com/19291616/109587347-e29d9180-7b41-11eb-9533-8c5774663c04.png)

**Comment by y1ndan** [comment]
兩個參數都需要在secret里設置，看日誌並好像沒有檢測到。
`TG_USER_ID`為數字型的用戶ID，若不知道是什麼，可搜尋@userinfobot 按提示操作，`id字段`即為`TG_USER_ID`

**Comment by NeiL978** [comment]
原來TG_USER_ID是要查才知道阿，我以為是一般的@XXXXX
我都在SECRET設定了，ID也改成數字ID了，但還是沒有啟動
後來把ACTION的workflow刪除重新設定一個就好了
謝謝
![image](https://user-images.githubusercontent.com/19291616/109630733-3a5aed80-7b80-11eb-8364-794c0e365fcb.png)
