### ISSUE TITLE
问下大佬存在多个推送目标的时候怎么办

### ISSUE THREAD

**Issue by Modurll** [y1ndan/genshin-impact-helper#151]
用参数 TG_USER_ID 设置两个值（中间用#隔开）的时候只会生效第一个，如果要生效多个的话应该要怎么做？是再设置一个secret还是只能生效一个？如果只能生效一个的话能否将参数值设置为群组ID？求大佬解答下，麻烦了!

**Comment by y1ndan** [comment]
一种推送方式只能对应单账号通知。

或许可以通过配置不同推送方式实现多账号通知
