### ISSUE TITLE
有没有可能加个微信推送的功能

### ISSUE THREAD

**Issue by MRDG001** [y1ndan/genshin-impact-helper#19]
先感谢大佬写的项目了！
大佬，在别的Fork的项目里可以绑定个微信推送的SCKEY，然后签到成功挺直观的。
（不知道为什么项目运行失败github不给我的邮箱发邮件）
如果是很麻烦的修改，那不好意思当我没说……现在的功能已经满足最关键需求了、、

**Comment by 2314933036** [comment]
微信推送就别想了,用谁的微信号,github的服务器在国外,怎么保证能登陆微信?原神是全球的,国外基本上也不用微信吧.
签到失败给个邮件提醒倒是可以有

**Comment by MRDG001** [comment]
> 微信推送就别想了,用谁的微信号,github的服务器在国外,怎么保证能登陆微信?原神是全球的,国外基本上也不用微信吧.
> 签到失败给个邮件提醒倒是可以有

不知道怎么形容微信推送的功能，我是fork一个b站签到的项目。那个项目的大佬使用了http://sc.ftqq.com/3.version  这个的自动推送，就成果而言像公众号推送一样，然后每次签到成功会来一个推送

**Comment by y1ndan** [comment]
> 先感谢大佬写的项目了！
> 大佬，在别的Fork的项目里可以绑定个微信推送的SCKEY，然后签到成功挺直观的。
> （不知道为什么项目运行失败github不给我的邮箱发邮件）
> 如果是很麻烦的修改，那不好意思当我没说……现在的功能已经满足最关键需求了、、

目前项目是运行失败github就会发送邮件通知的。你说的这个微信通知可以实现，但是不确定要不要加。

**Comment by y1ndan** [comment]
> 微信推送就别想了,用谁的微信号,github的服务器在国外,怎么保证能登陆微信?原神是全球的,国外基本上也不用微信吧.
> 签到失败给个邮件提醒倒是可以有

倒是很多项目使用方糖这个方案

**Comment by MRDG001** [comment]
> > 先感谢大佬写的项目了！
> > 大佬，在别的Fork的项目里可以绑定个微信推送的SCKEY，然后签到成功挺直观的。
> > （不知道为什么项目运行失败github不给我的邮箱发邮件）
> > 如果是很麻烦的修改，那不好意思当我没说……现在的功能已经满足最关键需求了、、
> 
> 目前项目是运行失败github就会发送邮件通知的。你说的这个微信通知可以实现，但是不确定要不要加。

好的，感谢大佬回复！

**Comment by 2314933036** [comment]
> > 微信推送就别想了,用谁的微信号,github的服务器在国外,怎么保证能登陆微信?原神是全球的,国外基本上也不用微信吧.
> > 签到失败给个邮件提醒倒是可以有
> 
> 不知道怎么形容微信推送的功能，我是fork一个b站签到的项目。那个项目的大佬使用了http://sc.ftqq.com/3.version 这个的自动推送，就成果而言像公众号推送一样，然后每次签到成功会来一个推送

好吧,是我孤陋寡闻了,没用过这个推送,这个建议自己魔改使用,毕竟不是每个人都需要这个功能
