### ISSUE TITLE
大佬问下那个设备id怎么查自己的啊

### ISSUE THREAD

**Issue by cumin-beef** [y1ndan/genshin-impact-helper#2]
![图片](https://user-images.githubusercontent.com/16508849/97529819-b1725080-19eb-11eb-8913-2abd2df123bb.png)
就这个
顺便cookie的格式感觉卡得比较死，如果复制成带中括号或者表格格式的就会报错

**Comment by y1ndan** [comment]
最直接的抓个包。如果想要唯一性，随意修改这里的数字就行。

**Comment by cumin-beef** [comment]
emmmm是对米游社的app抓包还是直接在网页上登录然后f12啊。。

**Comment by y1ndan** [comment]
米游社

**Comment by cumin-beef** [comment]
搞不来，随便改改算了- -
