### ISSUE TITLE
exit code 123

### ISSUE THREAD

**Issue by Ache1ous** [y1ndan/genshin-impact-helper#20]
大佬您好，

自从昨天更新后我依旧无法正常运行workflow。一直提示Process completed with exit code 123。更新cookie无效。希望大佬有空帮忙看看是什么原因。

谢谢。

**Comment by yinghualuowu** [comment]
似乎是没有拉取最新代码哦，请合并一下呢

**Comment by y1ndan** [comment]
我这边更新里之后需要你那边同步仓库才行。建议搜索`Github进行fork后如何与原仓库同步`
