### ISSUE TITLE
登录失效，请重新登录

### ISSUE THREAD

**Issue by qndydyhm** [y1ndan/genshin-impact-helper#26]
INFO {
  "result": "Failed",
  "message": "\"{'data': None, 'message': '登录失效，请重新登录', 'retcode': -100}\""
}
xargs: sh: exited with status 255; aborting
Error: Process completed with exit code 124.

目测米忽悠改了cookies格式？登陆失败

**Comment by 2314933036** [comment]
今天正常,应该是你登陆失效了,重新设置下cookie试试看

**Comment by y1ndan** [comment]
cookie 失效/无效

**Comment by qndydyhm** [comment]
> 
> 
> cookie 失效/无效
firefox获取的cookies重试了好几次均无效，尝试通过chrome获取则成功

**Comment by 136625346** [comment]
可能你用的验证码登录（）
