### ISSUE TITLE
大佬 请问怎么切换成签到B服的啊 两个服绑一个号的情况下

### ISSUE THREAD

**Issue by 516999395** [y1ndan/genshin-impact-helper#27]

**Comment by y1ndan** [comment]
以米游社为准，那里签到是那个服就是哪个服，怎么改可以咨询客服

**Comment by 516999395** [comment]
> 以米游社为准，那里签到是那个服就是哪个服，怎么改可以咨询客服

我网页上没有签到界面  手机上设置的是默认B服的  但是自动签到签的是官服的

**Comment by y1ndan** [comment]
那就是程序不完善，暂时没有办法签同时绑定两个服级以上的账号

**Comment by 516999395** [comment]
> 那就是程序不完善，暂时没有办法签同时绑定两个服及以上的账号

好吧 谢谢
