### ISSUE TITLE
希望可以加个server酱的推送

### ISSUE THREAD

**Issue by 2375399351** [y1ndan/genshin-impact-helper#33]
不知道后续有没有，但是还是希望可以加一个，比邮件方便多了

**Comment by 2314933036** [comment]
> 不知道后续有没有，但是还是希望可以加一个，比邮件方便多了

其实可以不用，签到时间弄到凌晨，每天开游戏时候有没有邮件不就可以知道有没有出问题了

**Comment by 2375399351** [comment]
> > 不知道后续有没有，但是还是希望可以加一个，比邮件方便多了
> 
> 其实可以不用，签到时间弄到凌晨，每天开游戏时候有没有邮件不就可以知道有没有出问题了

我目前看见那个时间是0 22 ***
是代表的几点签到啊？

**Comment by 2314933036** [comment]
> > > 不知道后续有没有，但是还是希望可以加一个，比邮件方便多了
> > 
> > 其实可以不用，签到时间弄到凌晨，每天开游戏时候有没有邮件不就可以知道有没有出问题了
> 
> 我目前看见那个时间是0 22 ***
> 是代表的几点签到啊？

格林尼治 22点

**Comment by 2375399351** [comment]
> > > > 不知道后续有没有，但是还是希望可以加一个，比邮件方便多了
> > > 
> > > 
> > > 其实可以不用，签到时间弄到凌晨，每天开游戏时候有没有邮件不就可以知道有没有出问题了
> > 
> > 
> > 我目前看见那个时间是0 22 ***
> > 是代表的几点签到啊？
> 
> 格林尼治 22点

ok谢谢了，那我设置成6是不是就上午6点签到了？

**Comment by 2375399351** [comment]
> > > > 不知道后续有没有，但是还是希望可以加一个，比邮件方便多了
> > > 
> > > 
> > > 其实可以不用，签到时间弄到凌晨，每天开游戏时候有没有邮件不就可以知道有没有出问题了
> > 
> > 
> > 我目前看见那个时间是0 22 ***
> > 是代表的几点签到啊？
> 
> 格林尼治 22点

懂了，22就是6点

**Comment by 2314933036** [comment]
> > > > > 不知道后续有没有，但是还是希望可以加一个，比邮件方便多了
> > > > 
> > > > 
> > > > 其实可以不用，签到时间弄到凌晨，每天开游戏时候有没有邮件不就可以知道有没有出问题了
> > > 
> > > 
> > > 我目前看见那个时间是0 22 ***
> > > 是代表的几点签到啊？
> > 
> > 格林尼治 22点
> 
> ok谢谢了，那我设置成6是不是就上午6点签到了？

你没算时差（

**Comment by 2314933036** [comment]
> > > > > 不知道后续有没有，但是还是希望可以加一个，比邮件方便多了
> > > > 
> > > > 
> > > > 其实可以不用，签到时间弄到凌晨，每天开游戏时候有没有邮件不就可以知道有没有出问题了
> > > 
> > > 
> > > 我目前看见那个时间是0 22 ***
> > > 是代表的几点签到啊？
> > 
> > 格林尼治 22点
> 
> ok谢谢了，那我设置成6是不是就上午6点签到了？

GMT+8才是北京时间

**Comment by shalinjie** [comment]
最简单的办法：
import下面加上sckey='server酱key'
logging.info(result)下面加上scsend(sckey, result)
就可以了

**Comment by shalinjie** [comment]
sorry上面少了一块
def scsend(SCKEY,message):
    sc_url='http://sc.ftqq.com/{}.send?text=标题&desp={}'.format(SCKEY,message)
    if sc_enable:
        r.get(url=sc_url)

**Comment by 2375399351** [comment]
> sorry上面少了一块
> def scsend(SCKEY,message):
> sc_url='[http://sc.ftqq.com/{}.send?text=标题&desp={}'.format(SCKEY,message)](http://sc.ftqq.com/%7B%7D.send?text=%E6%A0%87%E9%A2%98&desp=%7B%7D'.format(SCKEY,message))
> if sc_enable:
> r.get(url=sc_url)

感谢帮忙谢谢了
