### ISSUE TITLE
输出结果和code的不一致，提示pip等级过低？

### ISSUE THREAD

**Issue by ArgonCrystal** [y1ndan/genshin-impact-helper#45]
Actions页面点击Genshin Impact Helper-->build-->Run sign查看的结果最后提示这个信息，是需要我更新pip版本吗
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available. 
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.

**Comment by ArgonCrystal** [comment]
部署成功，是我粘贴cookie的环节出了问题

**Comment by berserkerzc** [comment]
我也是这样，重新在secret里面贴cookie就行了吗

**Comment by ArgonCrystal** [comment]
> 我也是这样，重新在秘密里面贴cookie就行了吗

首先密库取名必须是cookie，然后建议使用code里方法2的获取cookie命令获取cookie防止少复制，其它没有什么问题
