### ISSUE TITLE
Auto Sync Fork生效问题

### ISSUE THREAD

**Issue by ShallowAlex** [y1ndan/genshin-impact-helper#49]
请问Auto Sync Fork是强制fork的吗？如果自己仓库内修改了一些功能是否还能够自动更新？
顺便请教一下yml有比较好的教程吗？看大佬的文件某些关键语句和搜到的教程完全不一样

**Comment by Celeter** [comment]
想fork可以直接使用以下脚本，可以不用设置GITHUB_TOKEN
```
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
    - run: |
        git config --global user.name  github-actions
        git config --global user.email github-actions@github.com
        git remote add upstream https://github.com/y1ndan/genshin-impact-helper
        git remote -v
        git pull upstream master --allow-unrelated-histories
        git push origin master
```
教程的话看这个就行https://docs.github.com/cn/free-pro-team@latest/actions

**Comment by ShallowAlex** [comment]
> 想fork可以直接使用以下脚本(这个和本地拉取提交是一样的，代码冲突的话会执行失败)，可以不用设置GITHUB_TOKEN
> 
> ```
>     - name: Checkout master
>       uses: actions/checkout@v2
>       with:
>         ref: master
>         fetch-depth: 0
>     - run: |
>         git config --global user.name  github-actions
>         git config --global user.email github-actions@github.com
>         git remote add upstream https://github.com/y1ndan/genshin-impact-helper
>         git remote -v
>         git pull upstream master --allow-unrelated-histories
>         git push origin master
> ```
> 
> 多数情况只要会shell就行
> 教程的话看这个就行https://docs.github.com/cn/free-pro-team@latest/actions

好的谢谢
