### ISSUE TITLE
我actions里有genshin-impact-helper的名字，但是里面没内容是怎么回事

### ISSUE THREAD

**Issue by pakluk** [y1ndan/genshin-impact-helper#52]
我actions里有genshin-impact-helper的名字，但是里面没内容是怎么回事

**Comment by y1ndan** [comment]
第一次fork需要手动运行一次

**Comment by pakluk** [comment]
啊这，在哪里运行呢

**Comment by Sakurakouji-Runa** [comment]
> 啊这，在哪里运行呢

应该是在这里：Actions--Genshin Impact Helper--Run workflow--master--Run workflow

**Comment by pakluk** [comment]
已找到 谢谢
