### ISSUE TITLE
请在米游社App内打开~

### ISSUE THREAD

**Issue by wialny** [y1ndan/genshin-impact-helper#56]
昨天改了个密码, 今天收到邮件运行失败. 想起来应该是改密码导致COOKIE失效了, 于是复制了新的COOKIE重新运行就提示"请在米游社App内打开~"

2020-12-30T06:06:30 INFO {
  "result": "Failed",
  "message": "{\"data\": null, \"message\": \"请在米游社App内打开~\", \"retcode\": -1104}"
}
xargs: sh: exited with status 255; aborting
Error: Process completed with exit code 124.

更新代码后提示:
2020-12-30T05:19:55 INFO {
  "result": "Failed",
  "message": {
    "retcode": 0,
    "message": "OK",
    "data": {
      "list": [
        {
          "game_biz": "hk4e_cn",
          "region": "cn_gf01",
          "game_uid": "100***",
          "nickname": "***",
          "level": 52,
          "is_chosen": true,
          "region_name": "***岛",
          "is_official": true
        }
      ]
    }
  }
}
2020-12-30T05:19:55 INFO 未配置SCKEY,正在跳过推送...
2020-12-30T05:19:55 INFO 签到完成!
xargs: sh: exited with status 255; aborting
Error: Process completed with exit code 124.

配置SCKEY后提示:
2020-12-30T05:55:50 INFO {
  "result": "Failed",
  "message": {
    "retcode": 0,
    "message": "OK",
    "data": {
      "list": [
        {
          "game_biz": "hk4e_cn",
          "region": "cn_gf01",
          "game_uid": "100***",
          "nickname": "***",
          "level": 52,
          "is_chosen": true,
          "region_name": "***岛",
          "is_official": true
        }
      ]
    }
  }
}
2020-12-30T05:55:50 INFO 正在推送通知...
2020-12-30T05:55:54 INFO 推送通知成功
2020-12-30T05:55:54 INFO 签到完成!
xargs: sh: exited with status 255; aborting
Error: Process completed with exit code 124.

虽然后面提示有"签到完成", 但游戏内并没有收到签到邮件. 请问我这还有救吗?
还有我看那个什么SCKEY是微信推送用的, 我不需要可以不用设置吗?

**Comment by Chika99** [comment]
今天凌晨签到没事，下午签到同样遇到了签到出错，返回内容{'data': None, 'message
': '请在米游社App 内打开~', 'retcode': -1104}

**Comment by y1ndan** [comment]
据群员反馈，当前米游社网页版获取不到`account_id`和`cookie_token`了

**Comment by majesty17** [comment]
被官方封堵拉。。。求更。。

**Comment by AceNinja** [comment]
应该可以抓包获取token的吧~  只是藏在了不同的地方~

**Comment by qq57240** [comment]
> 据群员反馈，当前米游社网页版获取不到`account_id`和`cookie_token`了

看来只能用模拟器+fiddler试试了

**Comment by journey-ad** [comment]
抓包从app拿到cookie就可以了，签到逻辑并没有变化

**Comment by wialny** [comment]
请问是获取不到account_id和cookie_token还是说获取的account_id和cookie_token不对吗?
网页版的F12里还有account_id和cookie_token的

**Comment by karakoo** [comment]
可以使用HttpCanary+平行空间抓包获取account_id与cookie_token

**Comment by huaxianyan** [comment]
我用了 iOS 备用机和 Burp Suite 来抓包获取的

**Comment by 2375399351** [comment]
等个更新，加了ua之类的验证吧

**Comment by wialny** [comment]
发现了一个有意思的事情，不知道是成功签到了还是怎么了。
刚我打开米游社准备签到时发现今天已经签到，一看时间00：40？？
![Screenshot_20201231_125701_com mihoyo hyperion](https://user-images.githubusercontent.com/12374028/103395221-2edf4c00-4b68-11eb-8b3a-0373e7774fc1.jpg)
想了想，那时我好像还在抢救，可是明明报错了失败啊

**Comment by y1ndan** [comment]
> 网页版的F12里还有account_id和cookie_token的
是误报 浏览器问题 推荐使用Chrome获取

**Comment by y1ndan** [comment]
@wialny 有点囧 我把message写错了

**Comment by wialny** [comment]
上面这个00:40的是我同步dev分支后的结果, 看到失败我就回滚master了. 

今早6点的错误提示还是
2020-12-30T22:28:21 INFO 未配置SCKEY,正在跳过推送...
2020-12-30T22:28:21 INFO 签到完成!
xargs: sh: exited with status 255; aborting
Error: Process completed with exit code 124.

**Comment by Chika99** [comment]
> 我用了 iOS 备用机和 Burp Suite 来抓包获取的，但是还是提示「请在米游社App内打开~」

同从app中拿到cookie，签到接口还是提示在app中打开，但米游币任务可以正常完成

**Comment by qq57240** [comment]
确定是DS值计算方式被修改了，和以前一样会根据app_version值和系统时间来验证对应的加密字符串，现在唯一的办法是从网页版提取这个算法。在bbs.mihoyo.com/ys的任何一个帖子下点赞，会发送一个post请求，里面可以看到有app 2.3.0版本计算出来的值，这个算法代码肯定藏在js里，只是我拿不出来。一个是米社搞了反debug，然后估计代码也是高浓度雾化的，因为反debug部分就是高浓度base64雾化过的，去个反debug都搞了我一下午，搞不动了。

**Comment by y1ndan** [comment]
> 确定是DS值计算方式被修改了，和以前一样会根据app_version值和系统时间来验证对应的加密字符串，现在唯一的办法是从网页版提取这个算法。在bbs.mihoyo.com/ys的任何一个帖子下点赞，会发送一个post请求，里面可以看到有app 2.3.0版本计算出来的值，这个算法代码肯定藏在js里，只是我拿不出来。一个是米社搞了反debug，然后估计代码也是高浓度雾化的，因为反debug部分就是高浓度base64雾化过的，去个反debug都搞了我一下午，搞不动了。

2.1.0的算法不能用了

**Comment by povsister** [comment]
Maybe you have interest on this~
https://github.com/povsister/shell-toys/commit/b4e49c75642c8cc372f82917e28adc2454c104b8

**Comment by povsister** [comment]
One more thing: 
Does anybody know the signing algorithm used for app version >= 2.3.0 on native Android/iOS ? (client_type=1/2)

**Comment by y1ndan** [comment]
> One more thing:
> Does anybody know the signing algorithm used for app version >= 2.3.0 on native Android/iOS ? (client_type=1/2)

你这个不是2.3.0吗

**Comment by y1ndan** [comment]
> Maybe you have interest on this~
> [povsister/shell-toys@b4e49c7](https://github.com/povsister/shell-toys/commit/b4e49c75642c8cc372f82917e28adc2454c104b8)

你做的好！

**Comment by povsister** [comment]
> 你这个不是2.3.0吗

只是web，想要客户端的，瞄了一眼salt不一样，等一个逆向客户端的大佬

**Comment by journey-ad** [comment]
![image](https://user-images.githubusercontent.com/16256221/103415398-e2722b80-4bbc-11eb-9773-af112671cfe7.png)
好像来晚了😂 新的盐是上面那个值吗？

顺便一提可以把这个加成书签，点一下就能破解循环触发 debugger 的防 debug 策略
`javascript:(function(){var i=setTimeout(function(){while(--i)clearTimeout(h)})}())`

**Comment by povsister** [comment]
> 顺便一提可以把这个加成书签，点一下就能破解循环触发 debugger 的防 debug 策略
> `javascript:(function(){var i=setTimeout(function(){while(--i)clearTimeout(h)})}())`

dalao nb.  我哈搓搓的细看了生成算法，着实佩服米游社前端，他们基本上是弄出个密码本对照在解码，里边还有混淆内容... 盐那段甚至是分段解码拼起来的。。下一步估计就是定期自动更换密码本了，等一个dalao直接还原出算法，webpack打包后的结构实在太恶心了...

**Comment by qq57240** [comment]
> ![image](https://user-images.githubusercontent.com/16256221/103415398-e2722b80-4bbc-11eb-9773-af112671cfe7.png)
> 好像来晚了😂 新的盐是上面那个值吗？
> 
> 顺便一提可以把这个加成书签，点一下就能破解循环触发 debugger 的防 debug 策略
> `javascript:(function(){var i=setTimeout(function(){while(--i)clearTimeout(h)})}())`
啊！我还用fiddler伪造了js!学到了学到了！
顺便新的salt值虽然不知道怎么来的，但能用！已经可以自动签到了！

**Comment by qq57240** [comment]
> > 你这个不是2.3.0吗
> 
> 只是web，想要客户端的，瞄了一眼salt不一样，等一个逆向客户端的大佬

已经用上了这个盐值，可以正常签到了，well done!

**Comment by yinghualuowu** [comment]
> ![image](https://user-images.githubusercontent.com/16256221/103415398-e2722b80-4bbc-11eb-9773-af112671cfe7.png)
> 好像来晚了😂 新的盐是上面那个值吗？
> 
> 顺便一提可以把这个加成书签，点一下就能破解循环触发 debugger 的防 debug 策略
> `javascript:(function(){var i=setTimeout(function(){while(--i)clearTimeout(h)})}())`

我已经签到了没办法执行，但使用新的盐不会有接口错误，大概应该可能就是这个了，dalao~

**Comment by y1ndan** [comment]
> ![image](https://user-images.githubusercontent.com/16256221/103415398-e2722b80-4bbc-11eb-9773-af112671cfe7.png)
> 好像来晚了😂 新的盐是上面那个值吗？
> 
> 顺便一提可以把这个加成书签，点一下就能破解循环触发 debugger 的防 debug 策略
> `javascript:(function(){var i=setTimeout(function(){while(--i)clearTimeout(h)})}())`

tql!

**Comment by z13202013** [comment]
> ![image](https://user-images.githubusercontent.com/16256221/103415398-e2722b80-4bbc-11eb-9773-af112671cfe7.png)
> 好像来晚了😂 新的盐是上面那个值吗？
> 
> 顺便一提可以把这个加成书签，点一下就能破解循环触发 debugger 的防 debug 策略
> `javascript:(function(){var i=setTimeout(function(){while(--i)clearTimeout(h)})}())`

怎么拿到的新盐

**Comment by wialny** [comment]
我今天也自动签到成功的, 什么都没改, 还是用的昨天上午10:04的dev分支

Run pip install -r requirements.txt
Collecting requests==2.20.0
  Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<2.8,>=2.5
  Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.25,>=1.21.1
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2020.12.5 chardet-3.0.4 idna-2.7 requests-2.20.0 urllib3-1.24.3
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
2020-12-31T22:26:42 INFO 将在 118 秒后开始任务...
2020-12-31T22:28:40 INFO 任务开始
2020-12-31T22:28:40 INFO 准备获取账号信息...
2020-12-31T22:28:41 INFO 当前账号绑定了 1 个角色
2020-12-31T22:28:41 INFO 准备获取签到信息...
2020-12-31T22:28:43 INFO 准备为旅行者 1 号签到...
Region: 天空岛
UID: 100***204
2020-12-31T22:28:45 INFO 未配置SCKEY,正在跳过推送
2020-12-31T22:28:45 INFO 签到成功: ['\n    ##########2021-01-01##########\n    🔅[天空岛]100***204\n    今日奖励: 摩拉 × 5000\n    本月累签: 0 天\n    签到结果: OK\n    ##############################\n    ']
2020-12-31T22:28:45 INFO 任务结束

**Comment by Chika99** [comment]
新盐成功了，感谢上面几位大佬！

**Comment by TANJX** [comment]
大佬都太强了 等一波更新

**Comment by ceramshaw** [comment]
有dalao能给小白讲解一下现在该怎么做吗？
或者我应该等owner更新吗？
谢谢各位！

**Comment by zer0e** [comment]
> 我今天也自动签到成功了. 可我什么都没改啊, 还是用的昨天上午10:04的dev分支. 奇怪了
> 
> Run pip install -r requirements.txt
> Collecting requests==2.20.0
> Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
> Collecting certifi>=2017.4.17
> Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
> Collecting chardet<3.1.0,>=3.0.2
> Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
> Collecting idna<2.8,>=2.5
> Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
> Collecting urllib3<1.25,>=1.21.1
> Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
> Installing collected packages: urllib3, idna, chardet, certifi, requests
> Successfully installed certifi-2020.12.5 chardet-3.0.4 idna-2.7 requests-2.20.0 urllib3-1.24.3
> WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
> 2020-12-31T22:26:42 INFO 将在 118 秒后开始任务...
> 2020-12-31T22:28:40 INFO 任务开始
> 2020-12-31T22:28:40 INFO 准备获取账号信息...
> 2020-12-31T22:28:41 INFO 当前账号绑定了 1 个角色
> 2020-12-31T22:28:41 INFO 准备获取签到信息...
> 2020-12-31T22:28:43 INFO 准备为旅行者 1 号签到...
> Region: 天空岛
> UID: 100_**204 2020-12-31T22:28:45 INFO 未配置SCKEY,正在跳过推送 2020-12-31T22:28:45 INFO 签到成功: ['\n ##########2021-01-01##########\n 🔅[天空岛]100**_204\n 今日奖励: 摩拉 × 5000\n 本月累签: 0 天\n 签到结果: OK\n ##############################\n ']
> 2020-12-31T22:28:45 INFO 任务结束

我也没改今天也成功了

**Comment by qq57240** [comment]
> > 我今天也自动签到成功了. 可我什么都没改啊, 还是用的昨天上午10:04的dev分支. 奇怪了
> > Run pip install -r requirements.txt
> > Collecting requests==2.20.0
> > Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
> > Collecting certifi>=2017.4.17
> > Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
> > Collecting chardet<3.1.0,>=3.0.2
> > Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
> > Collecting idna<2.8,>=2.5
> > Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
> > Collecting urllib3<1.25,>=1.21.1
> > Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
> > Installing collected packages: urllib3, idna, chardet, certifi, requests
> > Successfully installed certifi-2020.12.5 chardet-3.0.4 idna-2.7 requests-2.20.0 urllib3-1.24.3
> > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> > You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
> > 2020-12-31T22:26:42 INFO 将在 118 秒后开始任务...
> > 2020-12-31T22:28:40 INFO 任务开始
> > 2020-12-31T22:28:40 INFO 准备获取账号信息...
> > 2020-12-31T22:28:41 INFO 当前账号绑定了 1 个角色
> > 2020-12-31T22:28:41 INFO 准备获取签到信息...
> > 2020-12-31T22:28:43 INFO 准备为旅行者 1 号签到...
> > Region: 天空岛
> > UID: 100_**204 2020-12-31T22:28:45 INFO 未配置SCKEY,正在跳过推送 2020-12-31T22:28:45 INFO 签到成功: ['\n ##########2021-01-01##########\n 🔅[天空岛]100**_204\n 今日奖励: 摩拉 × 5000\n 本月累签: 0 天\n 签到结果: OK\n ##############################\n ']
> > 2020-12-31T22:28:45 INFO 任务结束
> 
> 我也没改今天也成功了

因为脚本本就会从源仓库执行最新代码，而最新代码已经是更新好了的。

**Comment by zer0e** [comment]
> > > 我今天也自动签到成功了. 可我什么都没改啊, 还是用的昨天上午10:04的dev分支. 奇怪了
> > > Run pip install -r requirements.txt
> > > Collecting requests==2.20.0
> > > Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
> > > Collecting certifi>=2017.4.17
> > > Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
> > > Collecting chardet<3.1.0,>=3.0.2
> > > Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
> > > Collecting idna<2.8,>=2.5
> > > Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
> > > Collecting urllib3<1.25,>=1.21.1
> > > Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
> > > Installing collected packages: urllib3, idna, chardet, certifi, requests
> > > Successfully installed certifi-2020.12.5 chardet-3.0.4 idna-2.7 requests-2.20.0 urllib3-1.24.3
> > > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> > > You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
> > > 2020-12-31T22:26:42 INFO 将在 118 秒后开始任务...
> > > 2020-12-31T22:28:40 INFO 任务开始
> > > 2020-12-31T22:28:40 INFO 准备获取账号信息...
> > > 2020-12-31T22:28:41 INFO 当前账号绑定了 1 个角色
> > > 2020-12-31T22:28:41 INFO 准备获取签到信息...
> > > 2020-12-31T22:28:43 INFO 准备为旅行者 1 号签到...
> > > Region: 天空岛
> > > UID: 100_**204 2020-12-31T22:28:45 INFO 未配置SCKEY,正在跳过推送 2020-12-31T22:28:45 INFO 签到成功: ['\n ##########2021-01-01##########\n 🔅[天空岛]100**_204\n 今日奖励: 摩拉 × 5000\n 本月累签: 0 天\n 签到结果: OK\n ##############################\n ']
> > > 2020-12-31T22:28:45 INFO 任务结束
> > 
> > 
> > 我也没改今天也成功了
> 
> 因为脚本本就会从源仓库执行最新代码，而最新代码已经是更新好了的。

我的workflow文件用的是之前的，没有合并主仓库代码

**Comment by Kenny-Ch** [comment]
> > > 我今天也自动签到成功了. 可我什么都没改啊, 还是用的昨天上午10:04的dev分支. 奇怪了
> > > Run pip install -r requirements.txt
> > > Collecting requests==2.20.0
> > > Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
> > > Collecting certifi>=2017.4.17
> > > Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
> > > Collecting chardet<3.1.0,>=3.0.2
> > > Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
> > > Collecting idna<2.8,>=2.5
> > > Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
> > > Collecting urllib3<1.25,>=1.21.1
> > > Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
> > > Installing collected packages: urllib3, idna, chardet, certifi, requests
> > > Successfully installed certifi-2020.12.5 chardet-3.0.4 idna-2.7 requests-2.20.0 urllib3-1.24.3
> > > WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
> > > You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
> > > 2020-12-31T22:26:42 INFO 将在 118 秒后开始任务...
> > > 2020-12-31T22:28:40 INFO 任务开始
> > > 2020-12-31T22:28:40 INFO 准备获取账号信息...
> > > 2020-12-31T22:28:41 INFO 当前账号绑定了 1 个角色
> > > 2020-12-31T22:28:41 INFO 准备获取签到信息...
> > > 2020-12-31T22:28:43 INFO 准备为旅行者 1 号签到...
> > > Region: 天空岛
> > > UID: 100_**204 2020-12-31T22:28:45 INFO 未配置SCKEY,正在跳过推送 2020-12-31T22:28:45 INFO 签到成功: ['\n ##########2021-01-01##########\n 🔅[天空岛]100**_204\n 今日奖励: 摩拉 × 5000\n 本月累签: 0 天\n 签到结果: OK\n ##############################\n ']
> > > 2020-12-31T22:28:45 INFO 任务结束
> > 
> > 
> > 我也没改今天也成功了
> 
> 因为脚本本就会从源仓库执行最新代码，而最新代码已经是更新好了的。

为什么我还是不行，是要PR吗？

**Comment by ceramshaw** [comment]
我想请问一下现在cookie信息该怎么拿，用chrome的话还是不停跳debug，就算用上了楼上dalao的书签也一样

**Comment by Chika99** [comment]
> 我想请问一下现在cookie信息该怎么拿，用chrome的话还是不停跳debug，就算用上了楼上dalao的书签也一样

控制台document.cookie

**Comment by ceramshaw** [comment]
> > 我想请问一下现在cookie信息该怎么拿，用chrome的话还是不停跳debug，就算用上了楼上dalao的书签也一样
> 
> 控制台document.cookie

搞定了！谢谢大佬！
