### ISSUE TITLE
totalSignDay 值不正确

### ISSUE THREAD

**Issue by journey-ad** [y1ndan/genshin-impact-helper#71]
当天签到前取到的这个值实际上是上一次签到的累计天数，当天签到成功后需要+1，由此导致签到天数和奖励内容都错位了
```
##########2021-01-01##########
🔅[天空岛]*********
今日奖励: 摩拉 × 5000
本月累签: 0 天
签到结果: OK
##############################
```
因为下标-1取到了本月最后一天的奖励内容5000摩拉

相关代码：
https://github.com/y1ndan/genshin-impact-helper/blob/dev/genshin.py#L205-L206

**Comment by y1ndan** [comment]
对 这是签到之前发的请求，`totalSignDay`的值还没算上当天的
